name: Release Drafter

on:
  push:
    branches:
      - main
  pull_request:
    # pull_request event is required only for autolabeler
    types: [opened, reopened, synchronize]
  workflow_dispatch:

jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      # Drafts your next Release notes as Pull Requests are merged into "main"
      - uses: release-drafter/release-drafter@v6
        with:
          config-name: release_drafter.yml
          disable-autolabeler: true
          version: 2.0.0
          tag: 2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
